# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [9]:
# import numpy and pandas
import pandas as pd
import numpy as np
import scipy.stats as st
from scipy.stats import trim_mean, mode, skew, gaussian_kde, pearsonr, spearmanr, beta
from statsmodels.stats.weightstats import ztest as ztest

from scipy.stats import ttest_ind, norm, t
from scipy.stats import f_oneway
from scipy.stats import sem

# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents

In [2]:
# Run this code:
salaries = pd.read_csv('../data/Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [3]:
# Your code here
salaries.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

In [4]:
salaries.shape

(33183, 8)

# Challenge 2
This is a placeholder to make the AI corrector be able to find the correct exercise for feedback

# Challenge 3 - Constructing Confidence Intervals

We will test whether the hourly wage of all hourly workers is significantly different from $30/hr.

In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. Is $30/hr within that interval?

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [15]:
# Your code here
observed_mean = salaries['Hourly Rate'].mean()
observed_mean

np.float64(32.78855771628023)

In [22]:
salaries['Hourly Rate'].isna().sum()

np.int64(25161)

In [25]:
hourly = salaries['Hourly Rate'].dropna()

In [26]:
n = len(hourly)
n

8022

In [17]:
s = salaries['Hourly Rate'].std() 
s

12.11257268427681

In [27]:
st.t.interval(0.95,df=n-1,loc=observed_mean,scale=sem(hourly))

(np.float64(32.52345834488424), np.float64(33.05365708767622))

This is fine if we have thousands of worker data. But what if we have only 100 workers data?

Sample 100 workers and re-construct the 95% confidence interval. Is the interval wider of narrower? And why?
Do you still encapsulate the $30/hr mark in this case?

In [28]:
# Your code here 
salaries_sample = salaries.sample(100)
salaries_sample.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
4636,"CHAN, CONAN G",CIVIL ENGINEER IV,TRANSPORTN,F,Salary,NaN,87492.0,NaN
13484,"IGNACIO SILVESTRINI, EDGAR",DEPUTY DISTRICT CHIEF,FIRE,F,Salary,NaN,156360.0,NaN
21025,"NEGRETE, ZACHARY J",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,91080.0,NaN
6601,"DAVIS, DAVID E",OPERATING ENGINEER-GROUP A,GENERAL SERVICES,F,Hourly,40.0,NaN,47.44
13555,"IRIZARRY, EVELYN J",CROSSING GUARD,OEMC,P,Hourly,20.0,NaN,19.38

In [30]:
hourly_rate = salaries_sample['Hourly Rate'].dropna()

In [32]:
observed_mean = hourly_rate.mean()
observed_mean

np.float64(28.924800000000005)

In [33]:
s = hourly_rate.std(ddof = 1)
s

13.001694158839454

In [34]:
st.t.interval(0.95,100-1,loc=observed_mean,scale = s/np.sqrt(100))

(np.float64(26.344981805169937), np.float64(31.504618194830073))

 ### Is the interval wider or narrower? 
 - Wider
 ### And why? 
 - Because we need more leeway, and n is significantly smaller
 ### Do you still encapsulate the $30/hr mark in this case? 
 - Yes